services:
  db:
    image: postgres:12.3-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=my_test_app_dev_db
      - POSTGRES_PASSWORD=123321
    volumes:
      - my_test_app_dev_db-volume:/var/lib/postgresql/data
    ports:
      - 8901:5432

volumes:
  my_test_app_dev_db-volume: